### ISSUE TITLE
Simple example throws "unassignRoute is not a function"

### ISSUE THREAD

**Issue by urosgruber** [kazzkiq/svero#30]
I'm trying with some simple example from README but on accessing the page I get and error

```
TypeError: unassignRoute is not a function
    at onDestroy (/Users/uros/Sites/svelte-svero/example/public/App.js:812:5)
    at run (/Users/uros/Sites/svelte-svero/example/public/App.js:4:9)
    at Array.forEach (<anonymous>)
    at run_all (/Users/uros/Sites/svelte-svero/example/public/App.js:12:6)
    at Object.render (/Users/uros/Sites/svelte-svero/example/public/App.js:83:4)
    at /Users/uros/Sites/svelte-svero/example/server.js:10:24
    at Layer.handle [as handle_request] (/Users/uros/Sites/svelte-svero/example/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/uros/Sites/svelte-svero/example/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/uros/Sites/svelte-svero/example/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/uros/Sites/svelte-svero/example/node_modules/express/lib/router/layer.js:95:5)
```

**Comment by urosgruber** [comment]
It was built config issue and not everything was included, hence the error
